# Generated by Django 5.1.6 on 2025-04-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_capsule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormCapsule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='LetterTimeCapsule',
            new_name='LetterCapsule',
        ),
    ]
