# Generated by Django 5.1.6 on 2025-04-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_capsule', '0003_delete_formcapsule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCapsule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capsule_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='lettercapsule',
            name='date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lettercapsule',
            name='time',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lettercapsule',
            name='content',
            field=models.CharField(max_length=5000),
        ),
    ]
