# Generated by Django 5.1.6 on 2025-04-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_capsule', '0004_questioncapsule_lettercapsule_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettercapsule',
            name='date',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lettercapsule',
            name='time',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
