# Generated by Django 5.1.6 on 2025-04-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_capsule', '0005_alter_lettercapsule_date_alter_lettercapsule_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettercapsule',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='lettercapsule',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
