# Generated by Django 5.1.6 on 2025-04-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_capsule', '0006_alter_lettercapsule_date_alter_lettercapsule_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettercapsule',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='lettercapsule',
            name='time',
            field=models.TimeField(),
        ),
    ]
