# Generated by Django 5.1.6 on 2025-04-07 01:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_capsule', '0007_alter_lettercapsule_date_alter_lettercapsule_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncapsule',
            name='best',
            field=models.CharField(default='empty', max_length=1000),
        ),
        migrations.AddField(
            model_name='questioncapsule',
            name='book',
            field=models.CharField(default='empty', max_length=1000),
        ),
        migrations.AddField(
            model_name='questioncapsule',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='questioncapsule',
            name='dislikes',
            field=models.CharField(default='empty', max_length=1000),
        ),
        migrations.AddField(
            model_name='questioncapsule',
            name='foods',
            field=models.CharField(default='empty', max_length=1000),
        ),
        migrations.AddField(
            model_name='questioncapsule',
            name='future',
            field=models.CharField(default='empty', max_length=1000),
        ),
        migrations.AddField(
            model_name='questioncapsule',
            name='goals',
            field=models.CharField(default='empty', max_length=1000),
        ),
        migrations.AddField(
            model_name='questioncapsule',
            name='living',
            field=models.CharField(default='empty', max_length=1000),
        ),
        migrations.AddField(
            model_name='questioncapsule',
            name='memory',
            field=models.CharField(default='empty', max_length=1000),
        ),
        migrations.AddField(
            model_name='questioncapsule',
            name='message',
            field=models.CharField(default='empty', max_length=1000),
        ),
        migrations.AddField(
            model_name='questioncapsule',
            name='occupation',
            field=models.CharField(default='empty', max_length=1000),
        ),
        migrations.AddField(
            model_name='questioncapsule',
            name='show',
            field=models.CharField(default='empty', max_length=1000),
        ),
        migrations.AddField(
            model_name='questioncapsule',
            name='song',
            field=models.CharField(default='empty', max_length=1000),
        ),
        migrations.AddField(
            model_name='questioncapsule',
            name='time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='questioncapsule',
            name='weather',
            field=models.CharField(default='empty', max_length=1000),
        ),
        migrations.AddField(
            model_name='questioncapsule',
            name='year',
            field=models.CharField(default='empty', max_length=1000),
        ),
    ]
