# Generated by Django 5.1.6 on 2025-04-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_capsule', '0009_lettercapsule_user_questioncapsule_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lettercapsule',
            name='locked',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='questioncapsule',
            name='locked',
            field=models.BooleanField(default=True),
        ),
    ]
